window.SURPRISE_DATA = {
  compliments: {
    kicker: "50 petits mots de Gabin",
    title: "Un mot pour toi, Maman",
    button: "Découvrir un petit mot",
    items: [
      "Tu es ravissante aujourd'hui.",
      "Je suis heureux d'être ton fils.",
      "Si tes enfants sont incroyables, c'est grâce à toi.",
      "Je t'aime.",
      "Tu es très bien habillée aujourd'hui, dis donc.",
      "Tu es une maman géniale.",
      "Tu as un très joli sourire.",
      "Tu es belle.",
      "Tu es forte.",
      "Tu es vraiment drôle.",
      "Tu es gentille.",
      "Tu es attentionnée.",
      "Tu es importante pour moi.",
      "Je suis fier de toi.",
      "Tu peux être fière de toi.",
      "Aujourd'hui, profite bien : c'est ta journée.",
      "J'aime passer du temps avec toi.",
      "Ta famille a beaucoup de chance de t'avoir.",
      "Ton rire me fait sourire.",
      "Tu as beaucoup de charme.",
      "50 ans et toutes tes dents",
      "Tu seras une magnifique mariée.",
      "Franchement, tu ne fais pas tes 50 ans.",
      "Ça me fait toujours plaisir de te voir sourire.",
      "Tu as un grand cœur.",
      "Tu es une belle personne.",
      "Allez, aujourd'hui tu as bien le droit de ne rien faire.",
      "Tu es élégante.",
      "Tu es courageuse.",
      "Ton bonheur compte pour moi.",
      "Tu es précieuse.",
      "Tu es irremplaçable.",
      "J'aime te voir heureuse.",
      "T'as quand même plein de qualités, il faut bien l'avouer.",
      "Tu es parfaite comme tu es.",
      "Quand tu es là, c'est tout de suite plus sympa.",
      "Tu es une maman aimante.",
      "Je pense fort à toi.",
      "Je suis toujours content de te voir.",
      "Tu as une belle énergie.",
      "Tu as bonne mine aujourd'hui, dis donc.",
      "Tu es la meilleure des Lali.",
      "Tu es formidable.",
      "Aujourd'hui, c'est à nous de prendre soin de toi.",
      "Merci d'être ma maman.",
      "Je t'aime très fort.",
      "On est bien quand tu es là.",
      "Tu es unique.",
      "Joyeux 50 ans, Maman.",
      "Ne change rien, tu es super comme tu es."
    ]
  },
  treats: {
    kicker: "50 bons vraiment à ton goût",
    title: "La gourmandise de Lali",
    button: "Tirer une gourmandise",
    items: [
      "Bon pour une cuillère de Nutella, juste comme ça.",
      "Bon pour une cuillère de Nutella devant un épisode de Mentalist.",
      "Bon pour aller chercher le pot de Nutella pendant une soirée tranquille.",
      "Bon pour une deuxième cuillère de Nutella, parce que la première était trop petite.",
      "Bon pour une cuillère de Nutella à savourer sans avoir à te justifier.",
      "Bon pour quelques carrés de ta tablette de chocolat.",
      "Bon pour ouvrir une tablette de chocolat devant un film.",
      "Bon pour garder le dernier carré de chocolat pour toi.",
      "Bon pour une tablette de chocolat pendant une soirée canapé.",
      "Bon pour choisir entre un carré et toute la tablette de chocolat.",
      "Bon pour une poignée de M&M's devant ta série.",
      "Bon pour un paquet de M&M's rien que pour toi.",
      "Bon pour quelques M&M's pendant un film en famille.",
      "Bon pour reprendre des M&M's à la prochaine coupure entre deux épisodes.",
      "Bon pour choisir tes M&M's préférés en premier.",
      "Bon pour une pause KitKat bien méritée.",
      "Bon pour un KitKat devant Mentalist.",
      "Bon pour croquer un KitKat pendant une soirée tranquille.",
      "Bon pour un KitKat sans être obligée d'en donner un morceau.",
      "Bon pour aller chercher un KitKat dès que tu en as envie.",
      "Bon pour une glace devant un bon film.",
      "Bon pour choisir ton parfum de glace préféré.",
      "Bon pour manger une glace même si ce n'est pas vraiment l'heure.",
      "Bon pour une glace après une longue journée.",
      "Bon pour une soirée série avec une glace à la main.",
      "Bon pour un pot de Ben & Jerry's devant Mentalist.",
      "Bon pour choisir le Ben & Jerry's qui te fait le plus envie.",
      "Bon pour manger ton Ben & Jerry's directement dans le pot.",
      "Bon pour un Ben & Jerry's pendant une soirée rien qu'à toi.",
      "Bon pour finir le pot de Ben & Jerry's si le film est vraiment bon.",
      "Bon pour quelques carrés de Crunch bien croustillants.",
      "Bon pour une tablette de Crunch devant une série.",
      "Bon pour garder le dernier morceau de Crunch.",
      "Bon pour une pause Crunch au milieu de l'après-midi.",
      "Bon pour ouvrir un Crunch simplement parce que tu en as envie.",
      "Bon pour une barre de céréales pendant un épisode.",
      "Bon pour glisser une barre de céréales dans ton sac pour plus tard.",
      "Bon pour une barre de céréales quand tu veux une petite pause.",
      "Bon pour choisir ta barre de céréales préférée.",
      "Bon pour manger une barre de céréales tranquillement sur le canapé.",
      "Bon pour un verre de vin avec Thibaud.",
      "Bon pour un verre de Muscadet bien frais.",
      "Bon pour un verre de vin pendant un bon repas en famille.",
      "Bon pour savourer tranquillement un verre de vin après une longue journée.",
      "Bon pour un verre de vin devant un film avec la personne de ton choix.",
      "Bon pour un bol de chips devant Mentalist.",
      "Bon pour manger quelques chips directement dans le paquet.",
      "Bon pour sortir les chips pendant un film en famille.",
      "Bon pour garder les chips les plus croustillantes pour toi.",
      "Bon pour une soirée canapé, série et chips. Programme validé."
    ]
  }
};
